### ISSUE TITLE
ROM template: inline assembler syntax error

### ISSUE THREAD

**Issue by windship** [DamnedAngel/MSX-Templates-for-VisualStudio#52]
Followed this guide : https://docs.google.com/document/d/1Y2rTTMBN08Au59e44pzdX0ptVWfLfMgG1gp2e-KUVIE/edit
But various error occured when I load and tried to build a default template for ROM as you can see. 
Please check the attached screenshot.

What's wrong and what can I do for solve this? 

![image](https://github.com/DamnedAngel/MSX-Templates-for-VisualStudio/assets/24471913/d5eded3e-8d57-430b-8ccb-1d23bc0ed864)

**Comment by DamnedAngel** [comment]
Never mind about the errors in the "Error list" tab (last thing bottom left of  your screenshot). This is something I have yet to solve. A completely correct project will show these errors because the IDE doesn't really "know" z80 asm.
To verify whether your project successfully builds or not, check the messages in the "Output" tab, just to the right of the "Error list" tab. This tab will contain useful info on REAL errors if any.
All the projects just created by the templates generally compile correctly. Please let me know whether you are being able to successfully build you project. I will do my best to help.

**Comment by windship** [comment]
Thank you for quick reply!

I checked OUTPUT tap but it seems almost similar. Please check below:

Build started...
1>------ Build started: Project: menu, Configuration: Debug ARM ------
1>msxromapp.c
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(15,9): warning C4068: unknown pragma 'disable_warning'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(18,11): error C2400: inline assembler syntax error in 'opcode'; found 'hl'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(18,15): error C2014: preprocessor command must start as first nonwhite space
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(19,11): error C2065: 'add': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(19,11): error C2146: syntax error: missing ';' before identifier 'hl'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(19,13): error C2065: 'hl': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(20,3): error C2065: 'sp': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(20,3): error C2146: syntax error: missing ';' before identifier 'ld'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(20,7): error C2065: 'ld': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(20,7): error C2146: syntax error: missing ';' before identifier 'b'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(20,8): error C2065: 'b': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(20,13): error C2065: 'hl': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(21,3): error C2146: syntax error: missing ';' before identifier 'inc'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(21,8): error C2065: 'inc': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(21,8): error C2146: syntax error: missing ';' before identifier 'hl'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(22,3): error C2065: 'hl': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(22,3): error C2146: syntax error: missing ';' before identifier 'ld'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(22,7): error C2065: 'ld': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(22,7): error C2146: syntax error: missing ';' before identifier 'h'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(22,8): error C2065: 'h': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(22,13): error C2065: 'hl': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(23,3): error C2146: syntax error: missing ';' before identifier 'ld'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(23,7): error C2065: 'ld': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(23,7): error C2146: syntax error: missing ';' before identifier 'l'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(23,8): error C2065: 'l': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(25,3): error C2065: 'b': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(25,3): error C2146: syntax error: missing ';' before identifier '_printMSG_loop'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(26,7): error C2065: 'ld': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(26,7): error C2146: syntax error: missing ';' before identifier 'a'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(26,8): error C2065: 'a': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(26,13): error C2065: 'hl': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(27,3): error C2065: 'print': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(27,3): error C2146: syntax error: missing ';' before identifier 'or'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(27,7): error C2065: 'or': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(27,7): error C2146: syntax error: missing ';' before identifier 'a'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(28,3): error C2065: 'a': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(28,3): error C2146: syntax error: missing ';' before identifier 'ret'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(28,7): error C2065: 'ret': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(28,7): error C2146: syntax error: missing ';' before identifier 'z'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(29,3): error C2065: 'z': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(29,3): error C2146: syntax error: missing ';' before identifier 'push'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(29,8): error C2065: 'push': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(29,8): error C2146: syntax error: missing ';' before identifier 'hl'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(30,3): error C2065: 'hl': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(30,3): error C2146: syntax error: missing ';' before identifier 'push'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(30,8): error C2065: 'push': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(30,8): error C2146: syntax error: missing ';' before identifier 'ix'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(31,3): error C2065: 'ix': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(31,3): error C2146: syntax error: missing ';' before identifier 'ld'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(31,7): error C2065: 'ld': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(31,7): error C2146: syntax error: missing ';' before identifier 'iy'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(31,9): error C2065: 'iy': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(31,12): error C2014: preprocessor command must start as first nonwhite space
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(32,7): error C2065: 'ld': undeclared identifier
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(32,7): error C2146: syntax error: missing ')' before identifier 'ix'
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(32,11): error C2014: preprocessor command must start as first nonwhite space
1>C:\Users\windship\source\repos\menu\menu\msxromapp.c(33,8): error C2014: preprocessor command must start as first nonwhite space
1>Done building project "menu.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by DamnedAngel** [comment]
Something's really wrong with your project. Your build process is starting with 

`1>------ Build started: Project: menu, Configuration: Debug ARM ------`

But the templates don't have the ARM profile, and the make.bat build script seems not to be executed.

Did you create your project using VS Wizard, choosing the ROM template (correct), or did you create a random project and just dropped in your files (wrong, since this procedure does NOT configure the proper project profile and build script to be run)?

A proper build process would show something like this at the beginning:

```
Build started...
1>------ Build started: Project: MSX ROM Application, Configuration: Debug Win32 ------
1>-------------------------------------------------------------------------------
1>MSX SDCC Make Script Copyright © 2020-2023 Danilo Angelo 2021 Pedro Medeiros
1>version 00.06.00 alpha 1 - Codename Sam
1>Build Debug Level 150
1>-------------------------------------------------------------------------------
```

If this is not showing, then the build script is not being run. If it is not being run, it is likely you did not use VS project create wizard.

Perhaps you downloaded the "RAW" template, instead of the "VS Studio Template":
![image](https://github.com/DamnedAngel/MSX-Templates-for-VisualStudio/assets/4273372/7d91f02f-b3ca-4fe6-9098-5e7191954124)
If you did, then the integrations with the VS IDE are NOT present, and the VS project is configured with VS's default build process, which will likely produce precisely what you are experiencing. Make sure to download the proper VS template and install it on VS as instructed in GDocs' page 9.
If you used the RAW template, you should still be able to build your project outside VS using the build script manually, as described in GDocs' page 7:
![image](https://github.com/DamnedAngel/MSX-Templates-for-VisualStudio/assets/4273372/490b39af-8813-45c7-acd2-20b1d13dda21)

Things to try (in any order):
1. Recreate a new VS solution/project using the steps in GDocs' pages 10-15 (this wll only work properly if you installed the proper templates on VS, as described in GDocs's page 8-9). If it works, migrate your project files to this new solution/project.
2. Check whether the project's build configuration is correct:
![image](https://github.com/DamnedAngel/MSX-Templates-for-VisualStudio/assets/4273372/3a423740-aa23-4b22-935f-2ec63b33b307)
3.  Build your current project using the build script manually, as described in GDocs' page 7.

I strongly recommend that you insist on option #1 above, to make sure you get a working project from the templates, integrated with the IDE, and only then start gradually making changes to the source or moving in your existent sources, so you can know what step broke the build process.

Please let me know your findings.

**Comment by windship** [comment]
You're the man! 
Yeah there's some reason made problems like you said. I could succeed to build it after fix them, like as below:

* Download Visual Studio Template instead of RAW
* Using Win32 for configuration instead of ARM or X86
* Installing Python (I tried it before but it was failed)

![image](https://github.com/DamnedAngel/MSX-Templates-for-VisualStudio/assets/24471913/7bce0f5b-76a2-4086-8370-65a6c33a32f7)

Now I can start to make something. Thank you very much!

**Comment by DamnedAngel** [comment]
Nice! Have fun!
